version: "3.7"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: node:14.17.0
    ports:
      - 8000:8000
    volumes:
      - .:/code
      - '/code/node_modules'
    depends_on:
      - mysql_server

  mysql_server:
    image: mysql:8.0
    environment:
      MYSQL_DB: express_api_server
      MYSQL_HOST: localhost
      MYSQL_PASSWORD: 1q2w3e!Q
      MYSQL_ROOT_PASSWORD: 1q2w3e!Q

    
      