version: "3.7"

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: api-server
    networks:
      mysql-port:
        ipv4_address: 172.15.0.5
    ports:
      - 8080:8080
    depends_on:
      - mysql

  mysql:
    image: mysql:8.0
    environment:
      MYSQL_DB: ${SQL_DATABASE}
      MYSQL_HOST: ${SQL_HOST}
      MYSQL_ROOT_PASSWORD: ${SQL_PASSWORD}
    networks:
      mysql-port:
        ipv4_address: 172.15.0.8
    ports:
      - 3307:3306
    restart: always

volumes:
  mysql:

networks:
  mysql-port:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.15.0.0/16
    
      